name: sport_timer
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  freezed: ^2.4.7
  mockito: ^5.4.4
  bloc_test: ^9.1.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.19.0
  go_router: ^16.0.0
  gap: ^3.0.1
  injectable: ^2.5.1
  get_it: ^8.2.0
  audioplayers: ^6.5.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  shared_preferences: ^2.2.2

  basic_flutter_helper:
    git:
      url: https://github.com/alexaniko88/basic_flutter_helper.git
      ref: master
  lottie: ^3.0.0
  collection: ^1.18.0
  icons_launcher: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/animation/
    - assets/icons/

icons_launcher:
  image_path: "assets/icons/app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true